name: Simplified Video Generation Workflow

on:
  # Manual trigger with customizable parameters
  workflow_dispatch:
    inputs:
      duration:
        description: 'Duration to run in hours (0 for unlimited)'
        required: true
        default: '3.0'
      wait_minutes:
        description: 'Minutes to wait between video generations'
        required: true
        default: '2'
  
  # Run on schedule (once a day at 2 AM UTC)
  schedule:
    - cron: '0 2 * * *'

jobs:
  generate_videos:
    name: Generate Motivational Videos
    runs-on: ubuntu-latest
    timeout-minutes: 180  # 3 hours exactly
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Create required directories
        run: |
          mkdir -p output/images
          mkdir -p output/scripts
          mkdir -p output/audio
          mkdir -p output/videos
          mkdir -p credentials
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          # Google API packages
          pip uninstall -y google-generativeai || true
          pip install google-genai==0.1.0
          
          # Video generation packages
          pip install moviepy==1.0.3 decorator==4.4.2 imageio==2.9.0 imageio-ffmpeg==0.4.5
          pip install tqdm==4.64.1 numpy>=1.17.3 proglog==0.1.10
          
          # Audio generation
          pip install kokoro>=0.9.2
          
          # System dependencies
          sudo apt-get update
          sudo apt-get install -y ffmpeg libsndfile1 imagemagick espeak-ng
      
      - name: Display system and environment info
        run: |
          python --version
          pip list
          echo "Current directory:"
          ls -la
          echo "Source directory structure:"
          ls -la src/
          ls -la src/utils/
          ls -la src/generators/
      
      - name: Run diagnostic test
        run: |
          # Create a simple Python script to test the imports
          echo "import sys, os, traceback" > test_imports.py
          echo "print('Python version:', sys.version)" >> test_imports.py
          echo "print('Current directory:', os.getcwd())" >> test_imports.py
          echo "try:" >> test_imports.py
          echo "    import main" >> test_imports.py
          echo "    print('Successfully imported main module')" >> test_imports.py
          echo "    from src.utils.topic_data import get_random_topics" >> test_imports.py
          echo "    topics = get_random_topics(1)" >> test_imports.py
          echo "    print('Topics:', topics)" >> test_imports.py
          echo "    print('Running main function...')" >> test_imports.py
          echo "    result = main.main(auto_mode=True)" >> test_imports.py
          echo "    print('Main function completed')" >> test_imports.py
          echo "except Exception as e:" >> test_imports.py
          echo "    print('ERROR:', str(e))" >> test_imports.py
          echo "    traceback.print_exc()" >> test_imports.py
          echo "    print('Directory contents:', os.listdir('.'))" >> test_imports.py
          echo "    sys.exit(1)" >> test_imports.py
          
          # Run the test script
          python test_imports.py
      
      - name: Summary
        if: always()
        run: |
          echo "Workflow completed. Check logs for details."
